# Generated by Django 5.2.5 on 2025-12-22 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email_rrhh', models.EmailField(max_length=254, verbose_name='Correo RRHH para Notificaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('INICIO_COLACION', 'Inicio Colación'), ('FIN_COLACION', 'Fin Colación'), ('SALIDA', 'Salida')], default='ENTRADA', max_length=20)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, help_text='Dirección obtenida vía GPS', max_length=255, null=True)),
                ('hash_previo', models.CharField(blank=True, max_length=64)),
                ('hash_actual', models.CharField(blank=True, editable=False, max_length=64)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistencia.empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
