# Generated by Django 5.2.5 on 2025-12-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(blank=True, help_text='Ej: Jefe de Obra, Capataz', max_length=100, null=True),
        ),
    ]
