# Generated by Django 5.2.5 on 2025-12-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_perfil_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cambiar_pass_inicial',
            field=models.BooleanField(default=True, verbose_name='Debe cambiar contraseña'),
        ),
    ]
