# Generated by Django 5.2.5 on 2025-12-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_perfil_cambiar_pass_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='marcas/%Y/%m/'),
        ),
    ]
