# Generated by Django 5.2.5 on 2025-12-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0004_marcacion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='marcacion',
            name='alerta_olvido_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
