# Generated by Django 5.2.5 on 2026-01-07 17:11

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0005_marcacion_alerta_olvido_enviada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha del Feriado')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Nombre (ej: Navidad)')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados y Festivos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Comercial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/', verbose_name='Logo de la Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, help_text='Nombre legal ante el SII', max_length=200, null=True, verbose_name='Razón Social (Legal)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rut',
            field=models.CharField(blank=True, help_text='Ej: 76.123.456-K', max_length=12, null=True, verbose_name='RUT Empresa'),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='animo',
            field=models.CharField(blank=True, choices=[('FELIZ', 'Feliz'), ('NEUTRAL', 'Neutral'), ('MOLESTO', 'Molesto/Triste')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='comentario_animo',
            field=models.TextField(blank=True, null=True, verbose_name='¿Por qué te sientes así?'),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='es_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='estado',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('RECTIFICADA', 'Rectificada (Histórico)'), ('ANULADA', 'Anulada')], default='VIGENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='marca_reemplazada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reemplazo', to='asistencia.marcacion'),
        ),
        migrations.AddField(
            model_name='marcacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='hora_entrada',
            field=models.TimeField(default=datetime.time(9, 0), help_text='Hora límite antes de contar atraso.', verbose_name='Hora Entrada Oficial'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='jornada_diaria',
            field=models.IntegerField(default=9, help_text='Ej: 9 para jornada de 45 horas semanales.', verbose_name='Horas Jornada Diaria'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('TRABAJADOR', 'Trabajador'), ('EMPLEADOR', 'Empleador / RRHH'), ('FISCALIZADOR', 'Fiscalizador DT')], default='TRABAJADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_domingo',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_jueves',
            field=models.BooleanField(default=True, verbose_name='Jueves'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_lunes',
            field=models.BooleanField(default=True, verbose_name='Lunes'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_martes',
            field=models.BooleanField(default=True, verbose_name='Martes'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_miercoles',
            field=models.BooleanField(default=True, verbose_name='Miércoles'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_sabado',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='trabaja_viernes',
            field=models.BooleanField(default=True, verbose_name='Viernes'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.CharField(default=datetime.datetime(2026, 1, 7, 17, 11, 18, 12860, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DiaAdministrativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Solicitada')),
                ('tipo_jornada', models.CharField(choices=[('COMPLETO', 'Día Completo'), ('MAÑANA', 'Media Jornada (Mañana)'), ('TARDE', 'Media Jornada (Tarde)')], default='COMPLETO', max_length=10)),
                ('motivo', models.TextField(blank=True, help_text='Opcional: Trámites, personal, etc.', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Solicitud Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('comentario_rrhh', models.CharField(blank=True, max_length=200, null=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_administrativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LicenciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fin', models.DateField(verbose_name='Fecha Fin')),
                ('tipo', models.CharField(choices=[('ENFERMEDAD', 'Enfermedad Común'), ('ACCIDENTE', 'Accidente Laboral'), ('MATERNAL', 'Pre/Post Natal'), ('OTRO', 'Otro Motivo')], default='ENFERMEDAD', max_length=20)),
                ('documento', models.FileField(blank=True, null=True, upload_to='licencias/', verbose_name='Certificado PDF')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licencias', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Ausencia Laboral'), ('EXCESO_HORAS', 'Exceso de Horas Extras (+2h)')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('NUEVA', 'Nueva Marca (Falla Técnica)'), ('RECTIFICACION', 'Corregir Marca Existente')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('ACEPTADA', 'Aceptada por Trabajador'), ('RECHAZADA', 'Rechazada por Trabajador')], default='PENDIENTE', max_length=20)),
                ('fecha_hora_propuesta', models.DateTimeField()),
                ('tipo_marca_propuesta', models.CharField(max_length=20)),
                ('motivo', models.TextField(help_text='Motivo de la falla o error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marca_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asistencia.marcacion')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fin', models.DateField(verbose_name='Fecha Fin')),
                ('comentario', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Solicitud Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
            },
        ),
    ]
