# Generated by Django 5.2.5 on 2026-01-09 15:59

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0006_feriado_empresa_direccion_empresa_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='marcas/%Y/%m/'),
        ),
    ]
